# For nightly release. See .goreleaser.yml for normal release.
project_name: reviewdog

before:
  hooks:
    - go mod download

release:
  github:
    owner: reviewdog
    name: nightly
  # Do not set prerelease so that https://github.com/reviewdog/nightly/releases/latest always points to the latest version.
  prerelease: false

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/reviewdog/
    ldflags: -s -w -X github.com/sezzle/reviewdog/commands.Version={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - 386
      - amd64
      - arm
      - arm64

archives:
  - id: main
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"
