# reviewdog.yml

runner:
  golint:
    cmd: golint $(go list ./... | grep -v /vendor/)
    format: golint
  govet:
    cmd: go vet $(go list ./... | grep -v /vendor/)
    format: govet
  unused:
    cmd: unused $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  errcheck:
    cmd: errcheck -asserts -ignoretests -blank $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c:%m"
  gosimple:
    cmd: gosimple $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  staticcheck:
    cmd: staticcheck $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  misspell:
    cmd: misspell $(git ls-files)
    errorformat:
      - "%f:%l:%c: %m"
  unparam:
    cmd: unparam $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  revive:
    cmd: revive -config=.revive.toml $(go list ./... | grep -v /vendor/)
    format: golint
  golangci:
    cmd: golangci-lint run --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
