// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: metacomment.proto

package metacomment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a metadata of a diagnostic result.
// It's expected to be base64 encoded and included into reporter comments such
// as GitHub Pull Request Review comment.
//
// This metadata allow reviewdog to identify the same existing comment and
// avoid posting duplicated comments. It can also be used for resolving or
// deleting existing comments.
type MetaComment struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An unique identity, or "fingerprint", of the diagnostic result.
	Fingerprint string `protobuf:"bytes,1,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	// Source (tool) name of the diagnostic result.
	// It's important to have source name so that reviewdog can handle existing
	// comments with the same source properly.
	SourceName    string `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaComment) Reset() {
	*x = MetaComment{}
	mi := &file_metacomment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaComment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaComment) ProtoMessage() {}

func (x *MetaComment) ProtoReflect() protoreflect.Message {
	mi := &file_metacomment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaComment.ProtoReflect.Descriptor instead.
func (*MetaComment) Descriptor() ([]byte, []int) {
	return file_metacomment_proto_rawDescGZIP(), []int{0}
}

func (x *MetaComment) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *MetaComment) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

var File_metacomment_proto protoreflect.FileDescriptor

var file_metacomment_proto_rawDesc = string([]byte{
	0x0a, 0x11, 0x6d, 0x65, 0x74, 0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x64, 0x6f, 0x67, 0x2e, 0x72,
	0x64, 0x66, 0x22, 0x50, 0x0a, 0x0b, 0x4d, 0x65, 0x74, 0x61, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x20, 0x0a, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72,
	0x69, 0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x42, 0x32, 0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x64, 0x6f, 0x67, 0x2f, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x64, 0x6f, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x65, 0x74,
	0x61, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_metacomment_proto_rawDescOnce sync.Once
	file_metacomment_proto_rawDescData []byte
)

func file_metacomment_proto_rawDescGZIP() []byte {
	file_metacomment_proto_rawDescOnce.Do(func() {
		file_metacomment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metacomment_proto_rawDesc), len(file_metacomment_proto_rawDesc)))
	})
	return file_metacomment_proto_rawDescData
}

var file_metacomment_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metacomment_proto_goTypes = []any{
	(*MetaComment)(nil), // 0: reviewdog.rdf.MetaComment
}
var file_metacomment_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metacomment_proto_init() }
func file_metacomment_proto_init() {
	if File_metacomment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metacomment_proto_rawDesc), len(file_metacomment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metacomment_proto_goTypes,
		DependencyIndexes: file_metacomment_proto_depIdxs,
		MessageInfos:      file_metacomment_proto_msgTypes,
	}.Build()
	File_metacomment_proto = out.File
	file_metacomment_proto_goTypes = nil
	file_metacomment_proto_depIdxs = nil
}
