name: Go
on:
  push:
    branches:
      - master
  pull_request:
jobs:

  test:
    permissions:
      contents: read
    name: Test
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        fetch-depth: 50 # Need git history for testing.

    - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
      with:
        go-version-file: "go.mod"

    - name: Test
      run: go test -v -race -coverpkg=./... -coverprofile=coverage.txt ./...

    - uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
