name: Proto
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Built
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Build
      working-directory: proto/
      run: ./update.sh
    - name: Check diff
      run: git diff --exit-code
