name: Proto
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Built
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
    - name: Build
      working-directory: proto/
      run: ./update.sh
    - name: Check diff
      run: git diff --exit-code
