name: release test
on:
  push:
    branches:
      - master
      - release-*
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - .github/workflows/release_test.yml
      - ".goreleaser*.yml"
      - go.mod
      - go.sum

jobs:
  release_test:
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      # Setup Go for building reviewdog binary.
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: "go.mod"

      - name: Test goreleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: "~> v2"
          args: check
